version: '3.5'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: proxy
    depends_on:
      - frontend
      - backend

  frontend:
    image: ex1.10
    container_name: frontend
    environment:
      - API_URL=/api/

  backend:
    image: ex1.11
    container_name: backend
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=rootUserDB
      - DB_HOST=myDB
      - REDIS=redis
    depends_on:
      - myDB
      - redis
    
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: ex2.6-redis
  
  myDB:
    image: postgres
    container_name: ex2.6-DB
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=rootUserDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: