version: '3.5'

services:
  ex2.6-backend:
    image: ex1.11
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=rootUserDB
      - DB_HOST=myDB
      - REDIS=redis
    ports:
      - 8000:8000
    container_name: ex2.6-backend
    depends_on:
      - myDB
      - redis
  
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: ex2.6-redis
  
  myDB:
    image: postgres
    container_name: ex2.6-DB
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=rootUserDB