version: '3.5'

services:
  backend-server:
    image: ex1.11
    container_name: ex2.5-backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
  redis:
    image: redis
    container_name: ex2.5-redis
    ports:
      - 6379:6379